version: "3"

services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    ports:
      - "8081:80"
    volumes:
      - /opt:/srv
      - /opt/filebrowser/config:/config
    restart: unless-stopped
