version: "3.8"

services:
  db:
    image: mariadb:10.6
    container_name: nextcloud_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - /var/lib/docker/volumes/876195e34d98fb0d6b50c6a9234afe44f7f7fbdd02994c7f9bc525bd48abb22a/_data:/var/lib/mysql
    networks:
      - nextcloud_net

  app:
    image: nextcloud
    container_name: nextcloud_app
    restart: unless-stopped
    ports:
      - "${PORT}:80"
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_HOST: db
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - /opt/nextcloud/html:/var/www/html
    depends_on:
      - db
    networks:
      - nextcloud_net

networks:
  nextcloud_net:
    driver: bridge
