version: "3"

services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
      - /opt/uptime-kuma:/app/data
    ports:
      - "3001:3001"
