version: "3.8"

services:
  shortpaste:
    image: katlol/dockpaste:latest
    container_name: shortpaste
    ports:
      - "8090:8000"
    volumes:
      - shortpaste_data:/app/data
    environment:
      - PORT=8000
      - BASE_URL=http://localhost:8090
    restart: unless-stopped

volumes:
  shortpaste_data:
