version: "3.7"

services:
  metube:
    image: alexta69/metube
    container_name: metube
    ports:
      - "8085:8081"
    volumes:
      - /opt/metube/downloads:/downloads
    environment:
      - YTDL_OPTIONS={"writesubtitles":true,"subtitleslangs":["en"]}
    restart: unless-stopped
