version: "3.8"

services:
  quicklinks:
    image: ghcr.io/techno-tim/quicklink:latest
    container_name: quicklinks
    ports:
      - "9020:80"
    volumes:
      - quicklinks-data:/app/config
    restart: unless-stopped

volumes:
  quicklinks-data:
